# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Opentelemetry::Proto::Collector::Trace::V1::ExportTraceServiceResponse`.
# Please instead update this file by running `bin/tapioca dsl Opentelemetry::Proto::Collector::Trace::V1::ExportTraceServiceResponse`.

class Opentelemetry::Proto::Collector::Trace::V1::ExportTraceServiceResponse
  sig { void }
  def initialize; end
end
