source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in deprecated.gemspec.
gemspec

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"
